title: "NOAA-GFDL CM2-O Coupled Climate Model Simulations"
description: >
  
recipes:
  - id: "small"
    object: "recipe:small"
provenance:
  providers:
    - name: "NOAA-GFDL"
      description: "NOAA-GFDL"
      roles:
        - producer
        - licensor
      url: "https://mom-ocean.github.io/assets/pdfs/CM2_O_suite_1990_tutorial_and_analysis.pdf"
  license: "Unknown"
maintainers:
  - name: "Julius Busecke"
    orcid: "0000-0001-8571-865X"
    github: jbusecke
